### ISSUE TITLE
This is awesome 

### ISSUE THREAD

**Issue by HeyItsMicro** [Physuru/fwdhttpsd#2]
Congratulations on the release and this is so cool

**Comment by Physuru** [comment]
Micro

**Comment by Physuru** [comment]
hi

**Comment by HeyItsMicro** [comment]
I love you

**Comment by Physuru** [comment]
> I love you

Micro you are a Author. How good is it

**Comment by HeyItsMicro** [comment]
> > I love you
> 
> Micro you are a Author. How good is it

Sooo so good. @magnetardev

**Comment by HeyItsMicro** [comment]
@HeyItsMicro @Physuru

**Comment by Physuru** [comment]
LOL!

**Comment by HeyItsMicro** [comment]
#
Duplicate of #

**Comment by HeyItsMicro** [comment]
# # # I am learning GitHub

**Comment by magnetardev** [comment]
👍

**Comment by Physuru** [comment]
look micro that is great! youre a expert at github Already look at you go (online)

**Comment by HeyItsMicro** [comment]
> look micro that is great! youre a expert at github Already look at you go (online)

ThankYou! That is so SweetOfYou2Say✌️❤️

**Comment by Physuru** [comment]
Happy for you two

**Comment by HeyItsMicro** [comment]
WAIT HOW TF

**Comment by itss0n1c** [comment]
This is awesome

**Comment by HeyItsMicro** [comment]
I DIDNT TYPE THAT WHAT IS HAPPENING

**Comment by Physuru** [comment]
> This is awesome

Youre Awesome , pal,,,,,,

**Comment by Physuru** [comment]
> I DIDNT TYPE THAT WHAT IS HAPPENING

(Author)

**Comment by itss0n1c** [comment]
Physuru you're the first person I followed ever on here

**Comment by magnetardev** [comment]
> awesome

Awesome*

**Comment by HeyItsMicro** [comment]
Can you all follow me back I do really cool codes and issues

**Comment by Physuru** [comment]
> Physuru you're the first person I followed ever on here

Hi im actually with physuru right now irl

He said "Hi im actually with physuru right now irl

He said "Hi im actually with physuru right now irl

He said

**Comment by HeyItsMicro** [comment]
> > Physuru you're the first person I followed ever on here
> 
> Hi im actually with physuru right now irl
> 
> He said "Hi im actually with physuru right now irl
> 
> He said "Hi im actually with physuru right now irl
> 
> He said

I want to edit this

**Comment by HeyItsMicro** [comment]
Do I need your Passwords

**Comment by Physuru** [comment]
> Do I need your Passwords

YEAH!!!! ### 

> [``](url)
