### ISSUE TITLE
> I love you

### ISSUE THREAD

**Issue by HeyItsMicro** [Physuru/fwdhttpsd#5]
> I love you

Micro you are a Author. How good is it

_Originally posted by @Physuru in https://github.com/Physuru/fwdhttpsd/issues/2#issuecomment-932856217_

**Comment by HeyItsMicro** [comment]
I LOVE BEING AN AUTHOR!! SO GOOOD

**Comment by Physuru** [comment]
- [ ] haha theres a fuccin checkbox

**Comment by HeyItsMicro** [comment]
> [x] haha theres a fuccin checkbox

LMFAO WHAT? !

**Comment by itss0n1c** [comment]
Duplicate of #2

**Comment by Physuru** [comment]
> > I love you
thanks
